In [2]:
A=[" Peace to all politics"," Pray for the world ", "!!!  Way to go President Trump.  Keep those Dems guessing how you do such a great job.  They have not done much of anything in almost 4 years.  Sad","Great job ! Now if only those God forsaken protesters ... looters .. and rioters ... would actually get a real job the numbers would look even better !"," Many make promises, few deliver.","...and they said jobs wouldn't come back until the Fall. They forget who's in charge.","Democrats are scrambling trying to create something negative about jobs report."]

In [3]:
import pandas as pd
data = pd.DataFrame({'comment_text':A})

In [4]:
data['comment_text']

0                                Peace to all politics
1                                  Pray for the world
2    !!!  Way to go President Trump.  Keep those De...
3    Great job ! Now if only those God forsaken pro...
4                     Many make promises, few deliver.
5    ...and they said jobs wouldn't come back until...
6    Democrats are scrambling trying to create some...
Name: comment_text, dtype: object

In [5]:
#Number of Words
data['word_count'] = data['comment_text'].apply(lambda x: len(str(x).split(" ")))
data[['comment_text','word_count']].head()

                                        comment_text  word_count
0                              Peace to all politics           5
1                                Pray for the world            6
2  !!!  Way to go President Trump.  Keep those De...          33
3  Great job ! Now if only those God forsaken pro...          29
4                   Many make promises, few deliver.           6

In [5]:
#Number of characters
data['char_count'] = data['comment_text'].str.len() ## this also includes spaces
data[['comment_text','char_count']].head()

                                        comment_text  char_count
0                              Peace to all politics          22
1                                Pray for the world           20
2  !!!  Way to go President Trump.  Keep those De...         147
3  Great job ! Now if only those God forsaken pro...         151
4                   Many make promises, few deliver.          33

In [6]:
#Average Word Length
#Number of characters(without space count)/Total number of words
def avg_word(sentence):
  words = sentence.split()
  print(words)
  print(len(words))
  print(sum(len(word) for word in words))
  return (sum(len(word) for word in words)/len(words))

data['avg_word'] = data['comment_text'].apply(lambda x: avg_word(x))
data[['comment_text','avg_word']].head()

['Peace', 'to', 'all', 'politics']
4
18
['Pray', 'for', 'the', 'world']
4
15
['!!!', 'Way', 'to', 'go', 'President', 'Trump.', 'Keep', 'those', 'Dems', 'guessing', 'how', 'you', 'do', 'such', 'a', 'great', 'job.', 'They', 'have', 'not', 'done', 'much', 'of', 'anything', 'in', 'almost', '4', 'years.', 'Sad']
29
115
['Great', 'job', '!', 'Now', 'if', 'only', 'those', 'God', 'forsaken', 'protesters', '...', 'looters', '..', 'and', 'rioters', '...', 'would', 'actually', 'get', 'a', 'real', 'job', 'the', 'numbers', 'would', 'look', 'even', 'better', '!']
29
123
['Many', 'make', 'promises,', 'few', 'deliver.']
5
28
['...and', 'they', 'said', 'jobs', "wouldn't", 'come', 'back', 'until', 'the', 'Fall.', 'They', 'forget', "who's", 'in', 'charge.']
15
71
['Democrats', 'are', 'scrambling', 'trying', 'to', 'create', 'something', 'negative', 'about', 'jobs', 'report.']
11
69

                                        comment_text  avg_word
0                              Peace to all politics  4.500000
1                                Pray for the world   3.750000
2  !!!  Way to go President Trump.  Keep those De...  3.965517
3  Great job ! Now if only those God forsaken pro...  4.241379
4                   Many make promises, few deliver.  5.600000

In [7]:
#Number of stopwords
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')

data['stopwords'] = data['comment_text'].apply(lambda x: len([x for x in x.split() if x in stop]))
data[['comment_text','stopwords']].head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Vaishnavi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                        comment_text  stopwords
0                              Peace to all politics          2
1                                Pray for the world           2
2  !!!  Way to go President Trump.  Keep those De...         11
3  Great job ! Now if only those God forsaken pro...          6
4                   Many make promises, few deliver.          1

In [10]:
#Number of special characters
data['hastags'] = data['comment_text'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))
data[['comment_text','hastags']].head()

                                        comment_text  hastags
0                              Peace to all politics        0
1                                Pray for the world         0
2  !!!  Way to go President Trump.  Keep those De...        0
3  Great job ! Now if only those God forsaken pro...        0
4                   Many make promises, few deliver.        0

In [12]:
#Number of numerics
data['numerics'] = data['comment_text'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
data[['comment_text','numerics']].head()

                                        comment_text  numerics
0                              Peace to all politics         0
1                                Pray for the world          0
2  !!!  Way to go President Trump.  Keep those De...         1
3  Great job ! Now if only those God forsaken pro...         0
4                   Many make promises, few deliver.         0

In [13]:
#Number of Uppercase words
data['upper'] = data['comment_text'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
data[['comment_text','upper']].head()

                                        comment_text  upper
0                              Peace to all politics      0
1                                Pray for the world       0
2  !!!  Way to go President Trump.  Keep those De...      0
3  Great job ! Now if only those God forsaken pro...      0
4                   Many make promises, few deliver.      0

In [16]:
pos_family = {
    'noun' : ['NN','NNS','NNP','NNPS'],
    'pron' : ['PRP','PRP$','WP','WP$'],
    'verb' : ['VB','VBD','VBG','VBN','VBP','VBZ'],
    'adj' :  ['JJ','JJR','JJS'],
    'adv' : ['RB','RBR','RBS','WRB']
}

# function to check and get the part of speech tag count of a words in a given sentence
from textblob import TextBlob, Word, Blobber
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
def check_pos_tag(x, flag):
    cnt = 0
    try:
        wiki = TextBlob(x)
        for tup in wiki.tags:
            ppo = list(tup)[1]
            if ppo in pos_family[flag]:
                cnt += 1
                print(ppo, tup)
    except:
        pass
    return cnt

data['noun_count'] = data['comment_text'].apply(lambda x: check_pos_tag(x, 'noun'))
data['verb_count'] = data['comment_text'].apply(lambda x: check_pos_tag(x, 'verb'))
data['adj_count'] = data['comment_text'].apply(lambda x: check_pos_tag(x, 'adj'))
data['adv_count'] = data['comment_text'].apply(lambda x: check_pos_tag(x, 'adv'))
data['pron_count'] = data['comment_text'].apply(lambda x: check_pos_tag(x, 'pron'))
data[['comment_text','noun_count','verb_count','adj_count', 'adv_count', 'pron_count' ]].head()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Vaishnavi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Vaishnavi\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

NN ('Peace', 'NN')
NNS ('politics', 'NNS')
NN ('Pray', 'NN')
NN ('world', 'NN')
NN ('Way', 'NN')
NNP ('President', 'NNP')
NNP ('Trump', 'NNP')
NNP ('Keep', 'NNP')
NNP ('Dems', 'NNP')
NN ('job', 'NN')
NN ('anything', 'NN')
NNS ('years', 'NNS')
NN ('Sad', 'NN')
NN ('job', 'NN')
NNP ('God', 'NNP')
NNS ('protesters', 'NNS')
NNS ('looters', 'NNS')
NNS ('rioters', 'NNS')
NN ('job', 'NN')
NNS ('numbers', 'NNS')
NNS ('promises', 'NNS')
NN ('deliver', 'NN')
NNS ('jobs', 'NNS')
NNP ('Fall', 'NNP')
NN ('charge', 'NN')
NNPS ('Democrats', 'NNPS')
NN ('something', 'NN')
NNS ('jobs', 'NNS')
NN ('report', 'NN')
VB ('go', 'VB')
VBG ('guessing', 'VBG')
VBP ('do', 'VBP')
VBP ('have', 'VBP')
VBN ('done', 'VBN')
VBP ('..', 'VBP')
VB ('get', 'VB')
VB ('look', 'VB')
VBP ('make', 'VBP')
VBD ('said', 'VBD')
VB ('come', 'VB')
VBP ('forget', 'VBP')
VBZ ("'s", 'VBZ')
VBP ('are', 'VBP')
VBG ('scrambling', 'VBG')
VBG ('trying', 'VBG')
VB ('create', 'VB')
JJ ('great', 'JJ')
JJ ('Great', 'JJ')
JJ ('forsaken', 'JJ')
JJ ('real', 'JJ')
JJ ('Many', 'JJ')
JJ ('few', 'JJ')
JJ ('negative', 'JJ')
WRB ('how', 'WRB')
RB ('not', 'RB')
RB ('much', 'RB')
RB ('almost', 'RB')
RB ('Now', 'RB')
RB ('only', 'RB')
RB ('actually', 'RB')
RB ('even', 'RB')
RBR ('better', 'RBR')
RB ("n't", 'RB')
RB ('back', 'RB')
PRP ('you', 'PRP')
PRP ('They', 'PRP')
PRP ('they', 'PRP')
PRP ('They', 'PRP')
WP ('who', 'WP')

,comment_text,noun_count,verb_count,adj_count,adv_count,pron_count
0,Peace to all politics,2,0,0,0,0
1,Pray for the world,2,0,0,0,0
2,!!! Way to go President Trump. Keep those De...,9,5,1,4,2
3,Great job ! Now if only those God forsaken pro...,7,3,3,5,0
4,"Many make promises, few deliver.",2,1,2,0,0

In [17]:
data.head()

,comment_text,word_count,avg_word,stopwords,hastags,numerics,upper,noun_count,verb_count,adj_count,adv_count,pron_count
0,Peace to all politics,5,4.500000,2,0,0,0,2,0,0,0,0
1,Pray for the world,6,3.750000,2,0,0,0,2,0,0,0,0
2,!!! Way to go President Trump. Keep those De...,33,3.965517,11,0,1,0,9,5,1,4,2
3,Great job ! Now if only those God forsaken pro...,29,4.241379,6,0,0,0,7,3,3,5,0
4,"Many make promises, few deliver.",6,5.600000,1,0,0,0,2,1,2,0,0

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
cv=CountVectorizer()
A_vec = cv.fit_transform(A)
print(A_vec.toarray())

[[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
  0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0
  0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0 1 0
  0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0
  1 1]
 [0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 2 0 0 1
  1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 2 0
  0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0]
 [0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 2 0 0 0 0 1 0 1 0 0 1
  0 0]
 [1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0
  0 0]]

In [20]:
tv=TfidfVectorizer()
t_vec = tv.fit_transform(A)
print(t_vec.toarray())

[[0.         0.         0.53426056 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.53426056 0.53426056
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.37907384 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.53426056 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.53426056 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.37907384 0.         0.         0.         0.         0.
  0.         0.         0.         0.53426056 0.         0.
  0.         0.        ]
 [0.         0.         0.         0.20434289 0.         0.20434289
  0.         0.         0.         0.         0.         0.
  0.         0.         0.20434289 0.20434289 0.20434289 0.
  0.         0.         0.         0.         0.         0.
  0.20434289 0.         0.16962214 0.20434289 0.20434289 0.20434289
  0.         0.16962214 0.16962214 0.         0.20434289 0.
  0.         0.         0.         0.20434289 0.         0.20434289
  0.         0.         0.20434289 0.         0.         0.
  0.         0.20434289 0.         0.         0.         0.
  0.         0.20434289 0.         0.         0.         0.20434289
  0.         0.16962214 0.16962214 0.14498739 0.20434289 0.
  0.         0.20434289 0.         0.         0.         0.
  0.20434289 0.20434289]
 [0.         0.20274872 0.         0.         0.16829885 0.
  0.         0.         0.20274872 0.         0.         0.
  0.         0.         0.         0.         0.         0.20274872
  0.         0.         0.         0.         0.20274872 0.20274872
  0.         0.20274872 0.16829885 0.         0.         0.
  0.20274872 0.         0.3365977  0.         0.         0.20274872
  0.20274872 0.         0.         0.         0.         0.
  0.20274872 0.20274872 0.         0.20274872 0.         0.
  0.         0.         0.         0.20274872 0.20274872 0.
  0.20274872 0.         0.         0.         0.         0.
  0.14385628 0.         0.16829885 0.         0.         0.
  0.         0.         0.         0.         0.40549745 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.4472136  0.         0.         0.         0.         0.
  0.         0.4472136  0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.4472136  0.4472136  0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.4472136  0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.21930548 0.
  0.         0.26419613 0.         0.26419613 0.26419613 0.
  0.         0.         0.         0.         0.         0.
  0.26419613 0.         0.         0.26419613 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.21930548 0.         0.21930548 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.26419613 0.         0.         0.
  0.18745505 0.43861095 0.         0.         0.         0.
  0.26419613 0.         0.26419613 0.         0.         0.26419613
  0.         0.        ]
 [0.3132277  0.         0.         0.         0.         0.
  0.3132277  0.         0.         0.         0.         0.3132277
  0.         0.3132277  0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.26000589 0.         0.
  0.         0.         0.         0.         0.3132277  0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.3132277
  0.         0.         0.         0.3132277  0.3132277  0.
  0.         0.         0.         0.22224442 0.         0.3132277
  0.         0.         0.         0.         0.         0.
  0.         0.        ]]

In [21]:
feature_names = tv.get_feature_names()

dense = t_vec.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns=feature_names)

In [22]:
feature_names

['about',
 'actually',
 'all',
 'almost',
 'and',
 'anything',
 'are',
 'back',
 'better',
 'charge',
 'come',
 'create',
 'deliver',
 'democrats',
 'dems',
 'do',
 'done',
 'even',
 'fall',
 'few',
 'for',
 'forget',
 'forsaken',
 'get',
 'go',
 'god',
 'great',
 'guessing',
 'have',
 'how',
 'if',
 'in',
 'job',
 'jobs',
 'keep',
 'look',
 'looters',
 'make',
 'many',
 'much',
 'negative',
 'not',
 'now',
 'numbers',
 'of',
 'only',
 'peace',
 'politics',
 'pray',
 'president',
 'promises',
 'protesters',
 'real',
 'report',
 'rioters',
 'sad',
 'said',
 'scrambling',
 'something',
 'such',
 'the',
 'they',
 'those',
 'to',
 'trump',
 'trying',
 'until',
 'way',
 'who',
 'world',
 'would',
 'wouldn',
 'years',
 'you']

In [23]:
df_c =pd.concat([df,data], axis=1)
df_c.head()

,about,actually,all,almost,and,anything,are,back,better,charge,...,avg_word,stopwords,hastags,numerics,upper,noun_count,verb_count,adj_count,adv_count,pron_count
0,0.0,0.000000,0.534261,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,4.500000,2,0,0,0,2,0,0,0,0
1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,3.750000,2,0,0,0,2,0,0,0,0
2,0.0,0.000000,0.000000,0.204343,0.000000,0.204343,0.0,0.0,0.000000,0.0,...,3.965517,11,0,1,0,9,5,1,4,2
3,0.0,0.202749,0.000000,0.000000,0.168299,0.000000,0.0,0.0,0.202749,0.0,...,4.241379,6,0,0,0,7,3,3,5,0
4,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,...,5.600000,1,0,0,0,2,1,2,0,0